# netlify.toml - Configuration file for Netlify deployments

[build]
  publish = "dist"
  command = "npm run build"

# Configure proper MIME types for video files to ensure compatibility with Safari on iOS
[[headers]]
  for = "*.mp4"
  [headers.values]
    Content-Type = "video/mp4"

# Handle SPA routing - ensure all routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimize asset caching
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"